package json

import (
	"encoding/json"
	"log"

	"SkynetGo/social"
	"SkynetGo/util"
)

type AutoGenerated struct {
	NextPostID    int              `json:"next_post_id"`
	NextCommentID int              `json:"next_comment_id"`
	Avatar        string           `json:"avatar"`
	UserName      string           `json:"user_name"`
	Posts         []social.Post    `json:"posts"`
	Comments      []social.Comment `json:"comments"`
}

func RealJsonFromFile(filePath string) *AutoGenerated {

	var result AutoGenerated

	// read file
	dataString, err := util.ReadFile(filePath)
	if err != nil {
		log.Fatalln(err)
	}

	// parse json to struct
	json.Unmarshal([]byte(dataString), &result)

	return &result
}

func SaveJsonToFile(filePath string, objectToSave *AutoGenerated) error {

	// Struct to Json
	jsonByte, err := json.Marshal(objectToSave)
	if err != nil {
		return err
	}

	// Json byte to string
	jsonString := string(jsonByte)

	// save json string to file
	err = util.WriteFile(filePath, jsonString)
	if err != nil {
		return err
	}

	return nil
}
